name: hiroute
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - polars
  - pyarrow
  - duckdb
  - geopandas
  - shapely
  - pyproj
  - pyrosm
  - python-igraph
  - networkit
  - scikit-learn
  - pydantic
  - pyyaml
  - orjson
  - matplotlib
  - tqdm
  - pytest
  - pip
